### ISSUE TITLE
feat: transition to the marketplace cert-manager from our custom cert-manager

### ISSUE THREAD

**Issue by JoeHCQ1** [defenseunicorns/uds-bundle-software-factory-nutanix#200]
Right now, cert manager is deployed as our own little package. There is a uds-package-cert-manager repo, we should be using that.

**Comment by jacobbmay** [comment]
We are intentionally not using uds packages for cert manager or trust manager. Those services are needed before uds-core since applications deployed in core depend on CA bundles generated by trust manager. If we use the uds-packaged cert manager and trust manager they would need deployed after uds-core because they depend on uds runtime to deploy.

After discussing with uds-core team, trust manager wasn't something they were interested in adding to core so we have stuck with non uds-packaged versions of them to get around that chicken and egg problem
